@baseUrl = {{$dotenv BASE_URL}}
@authToken = {{login.response.body.token}}
# @name login
POST {{baseUrl}}/user/login
Content-Type: application/json

{
    "username": "{{$dotenv USERNAME}}",
    "password": "{{$dotenv PASSWORD}}"
}

###

GET {{baseUrl}}/media?sortBy=date-added&ascending=false
Authorization: Bearer {{authToken}}

###

POST {{baseUrl}}/media/96/convert
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "conversion title3"
    # "constantRateFactor": 28,
    # "forcePixelFormat": "yuv420p"
}

###

DELETE {{baseUrl}}/media/99
Authorization: Bearer {{authToken}}