FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

COPY . .

RUN dotnet restore
WORKDIR /app/Ghost.Web
RUN dotnet dev-certs https --trust
ENTRYPOINT ["dotnet", "watch", "run", "--urls=http://0.0.0.0:5120", "Ghost.Web/Ghost.Web.csproj"]