FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /app

COPY . .

RUN dotnet restore
WORKDIR /app/Ghost.Web
RUN dotnet dev-certs https --trust
RUN apt-get update && apt-get install -y ffmpeg
ENTRYPOINT ["dotnet", "watch", "run", "--urls=http://0.0.0.0:5120", "/app/Ghost.Web/Ghost.Web.csproj"]