@authToken = {{login.response.body.token}}
# @name login
POST {{host}}:{{port}}/api/user/login
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

###

POST {{host}}:{{port}}/api/library
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "main"
}

###

PUT {{host}}:{{port}}/api/library/1/add-paths
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "paths": ["/Users/kevinheritage/Movies"]
}

###

PUT {{host}}:{{port}}/api/library/1/sync
Authorization: Bearer {{authToken}}

###

PUT {{host}}:{{port}}/api/library/1/generate-thumbnails
Authorization: Bearer {{authToken}}

###

PUT {{host}}:{{port}}/api/library/1/generate-chapters
Authorization: Bearer {{authToken}}

### Get all libraries
GET {{host}}:{{port}}/api/library
Authorization: Bearer {{authToken}}