@authToken = {{login.response.body.token}}
# @name login
POST {{host}}:{{port}}/api/user/login
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

###

GET {{host}}:{{port}}/api/job
Authorization: Bearer {{authToken}}

###

DELETE {{host}}:{{port}}/api/job/26
Authorization: Bearer {{authToken}}

###

PUT {{host}}:{{port}}/api/job/5
Authorization: Bearer {{authToken}}

###

DELETE {{host}}:{{port}}/api/job/status/completed
Authorization: Bearer {{authToken}}